# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: anastasiia.sliusar@quantstack.net
author_name: Anastasiia Sliusar
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: custom-settings
mimetype: ''
mimetype_name: ''
project_short_description: Custom sesttings
python_name: custom_settings
repository: ''
test: true
viewer_name: ''

